#!/bin/sh

rm /etc/rc.d/rc3.d/S41data-provider-master
ln -sf /etc/rc.d/init.d/data-provider-master /etc/rc.d/rc3.d/S41data-provider-master

TMP=`which ps`
if [ $? -ne 0 ]; then
	exit 0
fi

TMP=`which aul_test`
if [ $? -ne 0 ]; then
	exit 0
fi



PID=`ps ax | grep 'data-provider-master' | grep -v 'grep' | grep -v 'dpkg' | grep -v 'dlogutil' | awk '{print $1}'`
if [ x"$PID" != x"" ]; then
	aul_test term_pid $PID
	sleep 1
fi

aul_test launch com.samsung.data-provider-master

# End of a file
