#!/bin/sh

launch_provider()
{
	while [ ! -f "/tmp/.stop.provider" ]; do
		/usr/bin/data-provider-master 
	done
	rm /tmp/.stop.provider
}

start ()
{
	launch_provider &
}

stop ()
{
	touch /tmp/.stop.provider
	PID=`ps ax | grep 'data-provider-master' | grep -v 'grep' | grep -v 'rpm' | grep -v 'dlogutil' | awk '{print $1}'`
	if [ x"$PID" != x"" ]; then
		KIL=`kill -9 $PID 2>&1 > /dev/null`
		KIL_RET=$?
		if [ $KIL_RET -ne 0 ]; then
			echo "Data provider is already stopped ($KIL_RET)"
		fi
		sleep 1
	fi
}

case "$1" in
	start|"") start;;
	stop) stop;;
	restart) stop; start;;
esac

# End of a file
