#!/bin/sh

start ()
{
	aul_test launch com.samsung.data-provider-master
}

stop ()
{
	PID=`ps ax | grep 'data-provider-master' | grep -v 'grep' | grep -v 'dlogutil' | awk '{print $1}'`
	if [ x"$PID" != x"" ]; then
		aul_test term_pid $PID
		sleep 1
	fi
}

case "$1" in
	start|"") start;;
	stop) stop;;
	restart) stop; start;;
esac

# End of a file
